language: csharp
dotnet: 3.1.101
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore ./Core/Core.csproj
  - dotnet restore ./Data/Data.csproj
  - dotnet restore ./UnitTests/UnitTests.csproj
  - dotnet test UnitTests
