name: .NET Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: |
        dotnet restore ./Core/Core.csproj
        dotnet restore ./Geometry/Geometry.csproj
        dotnet restore ./Data/Data.csproj
        dotnet restore ./UnitTests/UnitTests.csproj
    
    - name: Build core projects
      run: |
        dotnet build ./Core/Core.csproj --no-restore
        dotnet build ./Geometry/Geometry.csproj --no-restore
        dotnet build ./Data/Data.csproj --no-restore
        dotnet build ./UnitTests/UnitTests.csproj --no-restore
    
    - name: Test
      run: dotnet test UnitTests --no-restore --verbosity normal

  windows-build:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Note: .NET Framework 4.8 is included in the Windows runner image

    - name: Restore dependencies
      run: dotnet restore

    - name: Build all projects
      run: dotnet build --configuration Release --no-restore