name: .NET Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: |
        dotnet restore ./Core/Core.csproj
        dotnet restore ./Data/Data.csproj
        dotnet restore ./UnitTests/UnitTests.csproj
    
    - name: Build
      run: dotnet build UnitTests --no-restore
    
    - name: Test
      run: dotnet test UnitTests --no-restore --verbosity normal